name: ci

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - run: go install github.com/mfridman/tparse@latest
      - run: go install

      - run: go test ./... -cover -json > testresult.out
      - if: always()
        run: tparse -file=testresult.out -format markdown >> $GITHUB_STEP_SUMMARY
